### ISSUE TITLE
Sourcemaps incorrect line number

### ISSUE THREAD

**Issue by paradox37** [iFaxity/vite-plugin-istanbul#101]
### Describe the bug

As soon as I add this plugin to vite config, I get the wrong line number in browser Console in case of console.log or when unexpected error occurs, which is affecting debugging pretty much. 

I expect this plugin to does not affect sourcemaps in a way that points to a wrong line. You can see this behavior in stackblitz I provided. I used stackblitz template preset from ViteJs site, and just added this plugin and one `console.log`. 

Also, take a look at screen shot. Console says line 14, but it's actually 7.

![Screenshot 2023-05-09 at 14 09 22](https://github.com/iFaxity/vite-plugin-istanbul/assets/9640144/7f2bf20e-1221-4313-a626-580017ec4b31)
![Screenshot 2023-05-09 at 14 09 38](https://github.com/iFaxity/vite-plugin-istanbul/assets/9640144/34fde868-2f1d-417d-8762-54b2a7a1cd08)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-hcnpyq?terminal=dev

### Steps to reproduce

- Open stackblitz. 
- Check browser Console
- Click on the `App.tsx:14`
- It goes to line 14 instead of 7.

### System Info

```shell
Any system, any browser
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/iFaxity/vite-plugin-istanbul/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/iFaxity/vite-plugin-istanbul/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a vite-plugin-istanbul issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by iFaxity** [comment]
Hi @paradox37, big thanks for the issue.

I'll take a look at this and see what I can come up with.

The issue i feel might be that there is something that the underlying instrumenter is doing wrong (official istanbul-lib-instrument). As it is using babel to analyse the code it might affect the sourcemap as we use the returned sourcemap to match the coverage to the sourcemap.

Thanks!

**Comment by kota65535** [comment]
Same here. Is there any progress?

**Comment by iFaxity** [comment]
Please try out the new version to see if the fix is working in the pre release. And i will plan a stable release if it gets good responses.
