### ISSUE TITLE
Allow configuring `coverageGlobalScope`

### ISSUE THREAD

**Issue by MoLow** [iFaxity/vite-plugin-istanbul#103]
### Description

I desire to instrument an extension service worker (Manifest V3) where there is no global `window`

### Suggested solution

`coverageGlobalScope` should either be configurable and/or default to `globalThis`:
https://github.com/iFaxity/vite-plugin-istanbul/blob/e149b5aabac122af63ed1b81d1c99879ca2133e0/src/index.ts#L93

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/iFaxity/vite-plugin-istanbul/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by iFaxity** [comment]
Hi @MoLow, thanks for the issue!

Didn't think about this since the plugin wasn't really used in a context that was not a browser window (that I know of at least)

I'll review the PR and do some testing this week.
