### ISSUE TITLE
[bug] VITE_COVERAGE not taken into account if set in .env file

### ISSUE THREAD

**Issue by yann-combarnous** [iFaxity/vite-plugin-istanbul#12]
VITE_COVERAGE value is taken from process.env in this plugin. But according to https://vitejs.dev/guide/env-and-mode.html#env-files, we should be able to set env variables in .env files as well.

When setting VITE_COVERAGE in .env file, this plugin is not reading the value, if requireEnv is true.

**Comment by iFaxity** [comment]
Hi @yann-combarnous , yes this is unfortunately the case.
There seems to be a utility method in Vite to load env variables.

I will look into this and publish a new version once the fix is implemented.

**Comment by iFaxity** [comment]
Hello, this is now added with the new release v2.4.0 (4accd4a)
