### ISSUE TITLE
support coverage variable

### ISSUE THREAD

**Issue by Shangyunliang** [iFaxity/vite-plugin-istanbul#157]
### Description

i think coverageVariable can make instanbul have more useful feature. so  i want can add coverageVariable to options

### Suggested solution

add coverageVariable to options

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/iFaxity/vite-plugin-istanbul/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by iFaxity** [comment]
You can add a custom prefix via envPrefix. For example you can set `envPrefix: 'CUSTOM_'` to set the coverage variable to CUSTOM_COVERAGE whether coverage should be enabled or disabled.
