### ISSUE TITLE
doc: Update documentation to clarify what env means in requireEnv

### ISSUE THREAD

**Issue by clluiz** [iFaxity/vite-plugin-istanbul#16]
The description of the option requireEnv is not clear:

`Optional boolean to require env to be true to instrument to code, otherwise it will instrument even if env variable is not set`

Is env an environment variable? A environment file? If not where it should be defined?

**Comment by iFaxity** [comment]
Hi @clluiz, yes the documentation is not really in cleartext I'm sorry. I will correct it to clarify that it relates to the *VITE_COVERAGE* or *CYPRESS_COVERAGE* variable if the `cypress` configuration option is set to true.

**Comment by iFaxity** [comment]
So if `requireEnv` is set to **true**, the *VITE_COVERAGE* environment variable is required to be `true` in order for instrumentation to be permitted.

If however `requireEnv` is set to **false** (which is the default state), instrumentation is permitted if the *VITE_COVERAGE* environment variable is not set to **true**. So effectively the inverse.

**Comment by iFaxity** [comment]
Released in v2.5.1.
