### ISSUE TITLE
Warning is shown: The CJS build of Vite's Node API is deprecated

### ISSUE THREAD

**Issue by aimad-majdou** [iFaxity/vite-plugin-istanbul#209]
### Describe the bug

Upon migrating to Vite version 5, it has been discovered that the vite-plugin-istanbul package is generating a warning due to its usage of the deprecated CJS Node API. The warning originates from the node_modules/vite-plugin-istanbul/dist/index.cjs file:

![image](https://github.com/storybookjs/storybook/assets/16216620/5e1f7d5f-3eee-47b6-aec7-c2770ef71d36)

**Proposed Solution:**
Update the import statement in vite-plugin-istanbul to use dynamic imports, as recommended in the Vite documentation [here](https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated).

For additional infos please check this issue: https://github.com/storybookjs/storybook/issues/26291

### Reproduction

https://stackblitz.com/edit/github-wgldvd-tuuoti

### Steps to reproduce

Open the reproduction [url](https://stackblitz.com/edit/github-wgldvd-tuuoti), and observe  the warning message related to the deprecated CJS Node API usage, in the console after the project starts.

If you remove the `'@storybook/addon-coverage'` from `main.ts` the error will disappear.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 3.78 GB / 15.86 GB
  Binaries:
    Node: 21.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.81)
  npmPackages:
    @vitejs/plugin-react-swc: 3.6.0 => 3.6.0
    vite: 5.2.9 => 5.2.9
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/iFaxity/vite-plugin-istanbul/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/iFaxity/vite-plugin-istanbul/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a vite-plugin-istanbul issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by iFaxity** [comment]
Hi @aimad-majdou, thanks for the issue.

Absolutely, will look into this and upload a new major version to export using ES modules instead.
