### ISSUE TITLE
Does not install on non `v20` node versions

### ISSUE THREAD

**Issue by bhvngt** [iFaxity/vite-plugin-istanbul#214]
### Describe the bug

While upgrading this package on node v22, I get following error

`Your Node version is incompatible with "vite-plugin-istanbul@6.0.1".`.

I believe this is happening because of following line in `package.json`
https://github.com/iFaxity/vite-plugin-istanbul/blob/9fe59335209fa48ac03514d8088216f57394bc9a/package.json#L70

You may want to change this to `>=^20.12`

### Reproduction

NA

### Steps to reproduce

pnpm install vite-plugin-instanbul

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 261.92 MB / 32.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 22.1.0 - ~/Library/pnpm/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/4327_1713977399534/bin/yarn
    npm: 10.7.0 - ~/Library/pnpm/npm
    pnpm: 9.0.6 - ~/Library/pnpm/pnpm
    bun: 1.1.3 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 124.1.65.126
    Chrome: 124.0.6367.119
    Chrome Canary: 126.0.6460.0
    Safari: 17.4.1
```

### Used Package Manager

pnpm

### Logs
```
Your Node version is incompatible with "vite-plugin-istanbul@6.0.1".

Expected version: ^20.12.2
Got: v22.1.0

This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.
```
### Validations

- [X] Read the [Contributing Guidelines](https://github.com/iFaxity/vite-plugin-istanbul/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/iFaxity/vite-plugin-istanbul/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a vite-plugin-istanbul issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by iFaxity** [comment]
Hi @bhvngt, i see. Didn't think it would show up on installs but i'll remove it with a bugfix release in a little bit.
