### ISSUE TITLE
build failed in main branch

### ISSUE THREAD

**Issue by stevez** [iFaxity/vite-plugin-istanbul#25]
node version: 14.16.1
os: mac
branch : main
command: npm run build

 npm run build

> vite-plugin-istanbul@2.1.0 build /Users/s5474013/github/vite-plugin-istanbul
> tsc

node_modules/vite/dist/node/index.d.ts:51:47 - error TS2307: Cannot find module 'ws' or its corresponding type declarations.

51 import type { WebSocket as WebSocket_2 } from 'ws';
                                                 ~~~~

node_modules/vite/dist/node/index.d.ts:52:54 - error TS2307: Cannot find module 'ws' or its corresponding type declarations.

52 import { WebSocketServer as WebSocketServer_2 } from 'ws';
                                                        ~~~~

Found 2 errors in the same file, starting at: node_modules/vite/dist/node/index.d.ts:51

**Comment by iFaxity** [comment]
Hi @stevez, seems like you are using an older version of the plugin.

It could be that the vite version you have installed doesn't play well with some type declaration.

Could you try to upgrade your packages (especially vite and vite-plugin-istanbul) to a later version?

**Comment by stevez** [comment]
No, plugin is OK, but when I tried to build your source code from main branch. (version 2.1.0), I got the above error.

**Comment by iFaxity** [comment]
Aha, ok. I see now. I'll see if i get the same problem and what causes it.

**Comment by iFaxity** [comment]
I switched to the same node version on macOS and cant get the same error.

`christian<main> ~/GitHub/vite-plugin-istanbul node --version
v14.16.1
christian<main> ~/GitHub/vite-plugin-istanbul npm run build

> vite-plugin-istanbul@2.1.0 build /Users/christian/GitHub/vite-plugin-istanbul
> tsc

christian<main> ~/GitHub/vite-plugin-istanbul`

Please try to remove your `node_modules` directory and run `npm install` again.

**Comment by stevez** [comment]
I noticed the  "@types/node": "^16.3.1",  so I switched to node 16.3.0, and remove all the node_modules,
here is the npm list:
├── @semantic-release/changelog@5.0.1
├── @semantic-release/git@9.0.1
├── @types/node@16.11.17
├── chalk@4.1.2
├── istanbul-lib-instrument@4.0.3
├── test-exclude@6.0.0
├── typescript@4.5.4
└── vite@2.7.12

after that the build is successful.

for some reason before, I realize the issue I have is when I run npm install, the vite version was automatically upgraded to 2.9.1, maybe because I have another repo which uses 2.9.1?  It seems your repo can't support vite 2.9.1

**Comment by iFaxity** [comment]
Hmm, this could be the case. I'll test this and see if i get the same results.

**Comment by iFaxity** [comment]
Yes, i can confirm i get the same error now. 

It seems to be related to the package "ws" doesnt get installed, in fact multiple "dev" packages are not installed. I'll check if there is something i can do, but most likely its a problem with vite.

**Comment by iFaxity** [comment]
I've found a fix for this by including @types/ws as a dev dependency. I'll push it up as a minor release tomorrow.

**Comment by stevez** [comment]
works in the 2.7.1
