### ISSUE TITLE
Include all files in coverage report, not just the ones with test against them

### ISSUE THREAD

**Issue by yann-combarnous** [iFaxity/vite-plugin-istanbul#28]
We use Cypress for testing with Vite + this plugin, and run our tests in parallel.

As a tester, I would like to be able to get a global code coverage for all files selected by include/exclude options, not just the ones that have already tests against them. 

So if include/exclude results in files A, B and C, and my tests just cover file C, I want to see the code coverage for A, B and C, not just C.

NYC supports this option through the --all flag, see https://github.com/istanbuljs/nyc#selecting-files-for-coverage . This also seems supported by Istanbul Instrumenter Loader, see https://www.npmjs.com/package/istanbul-instrumenter-loader .

Not having this option is breaking running tests in parallel with Codecov or Coveralls, for instance, as merged reports are missing for different untested files in each test group.

**Comment by iFaxity** [comment]
This could be a tricky issue.

As this goes against how Vite works.
Vite only compiles the files that are imported. I would like to guess that if some files are not included in the tests this are actually not compiled by Vite and will not pass by the plugin.

I'm not really sure if there is a way around this but i would imagine that this is not really possible at the moment.
I know that the Vite team is looking into code coverage themselves and might fix this in the future.

**Comment by iFaxity** [comment]
After thinking about this for a white, i think this is not really do to this plugin and rather what reporter is used and how it is configured.

I don't have any experience with parallel tests, but would it not be the goal of the reporter to include the files that are not covered. As this plugin is only for instrumenting code and not for generating reports. Have you tested the following: https://github.com/cypress-io/code-coverage#exclude-files-and-folders

**Comment by yann-combarnous** [comment]
> 

Thanks. But I do not think the reporter can count covered / not covered lines / branches. Reporter are just reading `.nyc_output/out.json` file with stats from Istanbul and converting it into human/machine readable report.

So the trick could be to initialize `.nyc_output` for all files matching include/exclude. Not sure how to do this yet.

**Comment by yann-combarnous** [comment]
Actually, this is also discussed on Cypress side: https://github.com/cypress-io/code-coverage/issues/539

**Comment by yann-combarnous** [comment]
My workaround is to disable chunk-splitting in Vite using:
```
{
  rollupOptions: {
    output: {
      manualChunks: () => 'bundle',
    }
}
```

Otherwise with code splitting, Vite only parses the code files loaded by the tests.

**Comment by Emrald-TA** [comment]
I also am using Cypress with Vite + this plugin (all of this in a docker container) and wanted to achieve the same as @yann-combarnous . However the solution posted above did not work for me. @yann-combarnous if possible, could you explain your approach a bit further? I have a feeling that I am doing something wrong.

Just to be more specific about my question, below is what would like to know:

- How are you testing the preview version of your build with Cypress?
- Is there a way to disable code splitting without building?

**Comment by iFaxity** [comment]
Closed due to inactivity
