### ISSUE TITLE
[question]: The plugin works for e2e test coverage, but can not combine the unit test coverage result

### ISSUE THREAD

**Issue by stevez** [iFaxity/vite-plugin-istanbul#29]
1. The plugin works when I use playwright e2e test framework on the vite server, the coverage result is very close to the webpack + babel plugin; 
2.  My unit tests is using mocha + babel istanbul plugin + nyc, 
3. when I tried to merge the coverage results from both 1) and 2), the overall result is wrong.

I wonder how could I resolve this? I noticed the json file using your plugin includes the sourcemap, but my unit tests result do not have them, do you think this might cause the issue? and how can I include the source map in unit tests coverage?

**Comment by iFaxity** [comment]
Hi @stevez, this is weird indeed and not something i've run into before.

I'll see what i can find, however this is probably not anything related to this plugin rather in how code-coverage reporters works. Or rather the code-coverage merger.

It's also really hard to understand/debug without having any of the data of how the coverage files looks like.

**Comment by yann-combarnous** [comment]
@stevez , I think you run into the same issue as I do, see #28 .

**Comment by stevez** [comment]
I finally find a workaround: I used babel istanbul plugin inside the vite react plugin, for example in vite.config.js
```
plugins: [
    react(
      {
        babel: {
            plugins: [
                ["istanbul"],
            ],
        },
    }
    ),
  ],
```
I found this solution in the stackoverflow, it is a very smart trick.
Since my unit tests are instrumented by using babel istanbul plugin, in this way both unit tests and playwright tests are using the same way for the instrument, the 2 tests coverage merging works finally.

**Comment by stevez** [comment]
> @stevez , I think you run into the same issue as I do, see #28 .

I feel it is a different issue, in my use case the coverage json file includes all the source files, it seems fine for me.

**Comment by iFaxity** [comment]
Closing as the original issue has a workaround

**Comment by VasylQA** [comment]
@stevez could you please share all configurations and setting of how you made E2E Playwright tests work with this plugin?
And how are you processing results?

**Comment by stevez** [comment]
@VasylQA, it ended up it didn’t use this plugin, here is how I used:
plugins: [
    react(
      {
        babel: {
            plugins: [
                ["istanbul"],
            ],
        },
    }
    ),
  ],
