### ISSUE TITLE
feat: add envPrefix vite config support for env variable

### ISSUE THREAD

**Issue by kdhttps** [iFaxity/vite-plugin-istanbul#41]
## Describe the issue
I have `envPrefix: "FRONTEND_"` config in my `vite.config.ts`. Due to this `VITE_COVERAGE` env is not really working which is hardcoded in this plugin. This plugin should support env as pe `envPrefix` config.

## Steps To Reproduce
1. configure this plugin
1. add `VITE_COVERAGE=true` (or `FRONTEND_COVERAGE=true`) in `.env` file
1. update `envPrefix: "FRONTEND_"` in `vite.config.ts`
1. run `npm run dev`
1. plugin will fail to instrument the code because it will fail to find `VITE_COVERAGE` env because of `envPrefix: "FRONTEND_"`

## Expected behavior
The plugin should accept the `envPrefix: "FRONTEND_"` and env variable `FRONTEND_COVERAGE`

## Actual behavior
Plugin failed to get `VITE_COVERAGE=true` because of vite config `envPrefix: "FRONTEND_"`

Thank you!

**Comment by iFaxity** [comment]
Hi @kdhttps, thanks for submitting this issue.

Great finding! Didn't know there was a way to modify the prefix from config.
I'll work on a fix during the weekend.

**Comment by iFaxity** [comment]
Release target within a few days.
