### ISSUE TITLE
Istanbul ignore doesn't work?

### ISSUE THREAD

**Issue by thednp** [iFaxity/vite-plugin-istanbul#48]
Sup folks, thanks for your hard work!!

I recently started working on vite compilers and a new Cypress v10 implementation, after some time of tinkering I finally made it work.

The problem is that ignore istanbul directives don't work, neither of them, for instance here is `/* istanbul ignore else */`

![image](https://user-images.githubusercontent.com/6761246/186347170-5ad04759-8331-41ee-9873-f5a851eaccb5.png)

Any way to tell vite/esbuild to stop removing comments, I found this might be the issue?

**Comment by iFaxity** [comment]
Hello @thednp, thanks for the issue!

I will test this and return with my findings.
It could have something to do with another plugin that squashes the comments before the istanbul plugin gets the code. Therefore erasing any comments in the file.

As Vite does do some minification of the code this could be due to that.
But these are purely theories.

**Comment by thednp** [comment]
I'm working on an esbuild version of an instanbul plugin and I made it work after some couple hours. Right now, I think as a Typescript itself can be used to create a custom pipeline, perhaps something in Vite can speed that to the max 👍

**Comment by thednp** [comment]
@iFaxity if this helps you, have a look at my latest [transpiler setup](https://github.com/thednp/shorty/tree/master/cypress/plugins).

**Comment by alexgschwend** [comment]
Has there been any progress made on this problem? I am experiencing the same issue as well.

**Comment by kpdecker** [comment]
https://vitest.dev/guide/coverage#ignoring-code the vitest coverage documentation outlines a workaround.

**Comment by iFaxity** [comment]
Closed due to inactivity.
