### ISSUE TITLE
Disable plugin during SSR

### ISSUE THREAD

**Issue by edikdeisling** [iFaxity/vite-plugin-istanbul#50]
I have a problem with the plugin during SSR.
The plugin injects code with a `window` inside and this doesn't work in the node. The error is:
```
ReferenceError: window is not defined
    at cov_16v5xmsk37 (/src/entry-server.js:3:184)
    at eval (/src/entry-server.js:4:75)
    at instantiateModule (file:///Users/ed/Projects/github/vite/packages/vite/dist/node/chunks/dep-161621a1.js:55599:15)
```

I can't simply turn it off, because I need this plugin to work during middleware transformation(`app.use(vite.middlewares)`). So the issue only with modules handled during `vite.ssrLoadModule(...)`.

Vite passes `ssr` flag inside plugin `transform` function. It feels that it makes sense to skip all transformations during ssr.

To reproduce the issue:
1.`git clone git@github.com:vitejs/vite.git` - Clone vite repo
2.`cd vite` + `pnpm i` + `pnpm run build` - Install deps
3.`cd playground/ssr-vue` + `pnpm i vite-plugin-istanbul` - Go to the playground and install the plugin
4. Add plugin to `vite.config.js`
![image](https://user-images.githubusercontent.com/41228762/197188433-41169214-546a-40ef-baa2-1afb3c5c276f.png)
5. `pnpm run dev` - start server and open the browser

Maybe I'm wrong and this issue can be handled in a different way. Thank you!

**Comment by iFaxity** [comment]
Hello @edikdeisling, thanks for the issue!

Absolutely i've not used the plugin on an SSR project before so this is something I've completely overlooked.
I'll look into adding the ssr check within the transform and send out a fix for it when it's ready.

**Comment by rathorevaibhav** [comment]
hey any update on this? Or is there any workaround in the meantime? I'm using a Nuxt3 project and getting the same error for the window object.

**Comment by edikdeisling** [comment]
@rathorevaibhav you can wrap the plugin that way and use the wrapper. It works for me

```
import { Plugin } from 'vite';
import istanbulPlugin from 'vite-plugin-istanbul';

// TODO: remove this wrapper after issue would be done
// https://github.com/iFaxity/vite-plugin-istanbul/issues/50
export function istanbul(): Plugin {
  const plugin = istanbulPlugin({
    ...
  });

  return {
    ...plugin,
    transform(code, id, options) {
      if (options?.ssr) {
        return;
      }

      // @ts-ignore
      return plugin.transform.call(this, code, id, options);
    },
  };
}
```

**Comment by rathorevaibhav** [comment]
hey @edikdeisling @iFaxity 

My understanding of `options.ssr` is that it's a global property, meaning it will return `true` if I've enabled SSR in my application. If that's the case, I don't think it will transform any files right, because `options.ssr` will be true for all. Doesn't that contradict the very purpose of this plugin to instrument the code?

Or maybe my understanding of `options.ssr` is incomplete. Let me know!

The Nuxt3 app where I'm trying to implement this plugin compiles all the files into two versions, one for the client side and one for the SSR server side. I only want the server copies to NOT have instrumented code. The client copies should have the coverage function defined.

**Comment by edikdeisling** [comment]
@rathorevaibhav I think that it will work as you want. When you serve SSR application through Vite you have client-side components and server-side components(which loading through vite.ssrLoadModule). So SSR=true will be only for server-side components.

The same story for a build. You build server-side and client-side applications independently. So ssr=true will be for server-part only

**Comment by iFaxity** [comment]
@rathorevaibhav It is as @edikdeisling, i think you are mixing ssr from config and the options that are passed to the transform.

In a Vite plugin the transform has 3 parameters, [link to typings](https://github.com/vitejs/vite/blob/57916a476924541dd7136065ceee37ae033ca78c/packages/vite/src/node/plugin.ts#L166-L172).

The last parameter here are options passed to the transform. This gets set to `{ ssr: true }` if Vite is bundling a file that is executed by the server. So as long as the option that is passed into the transform is checked and not the one defined in Vite config it should be good.

**Comment by edikdeisling** [comment]
@iFaxity yeah, I meant exactly that) We'll have ssr in the transform hook only for server-proceed files

**Comment by rathorevaibhav** [comment]
@iFaxity @edikdeisling thanks for your explanation and for the new release!

With the latest version, the error `window is not defined` is does not appear anymore, however, I've hit a roadblock with the added fix. My Nuxt3 app is not getting compiled properly, and even though there are no errors in terminal when I run `npm run dev`, on browser, the raw Vue code appears. 

For reference, here's a screenshot from Chrome Element Inspector:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/12053186/203904076-925fe65f-83d5-44d3-8e3a-609de48a397f.png">

As you see, the `NuxtLink` should've been compiled properly to an anchor tag. This is happening with the latest fix. As soon as I go back to previous package version or manually remove the `options.ssr` check from node_modules, my app is getting compiled properly.

Do you happen to know the reason and how I can fix this?

**Comment by rathorevaibhav** [comment]
@edikdeisling thanks. Though I'm getting `options.ssr` value as both true & false for different files, it does seems like something related to Nuxt. I'll try checking in the Nuxt3 community.
