### ISSUE TITLE
Does it work on Cypress 10?

### ISSUE THREAD

**Issue by astagi** [iFaxity/vite-plugin-istanbul#51]
Hi,

I'm trying to use this plugin on Cypress 10, but it seems not working as expected.

I tried to configure it

```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import istanbul from 'vite-plugin-istanbul'

export default defineConfig({
    build: {
        sourcemap: true
    },
    plugins: [
        vue(),
        istanbul({
            include: 'src/*',
            exclude: ["node_modules", "cypress/", "**/tests/*"],
            extension: [".ts", ".vue"],
            cypress: true,
            requireEnv: false,
        })
    ]
})
```

anyway `window.__coverage__` is still empty and no instrumented code has been generated :(

**Comment by astagi** [comment]
Update number 3: I tried to modify your code and make the plugin acting on `window.parent`, cause the code is executed inside an `iframe`

```js
  const instrumenter = istanbulLibInstrument.createInstrumenter({
    coverageGlobalScopeFunc: false,
    coverageGlobalScope: "window.parent",
    preserveComments: true,
    produceSourceMap: true,
    autoWrap: true,
    esModules: true
  });
```

Now, `window.__coverage__` gets populated but again I get no coverage data exported on my file system 😞

**Comment by astagi** [comment]
@iFaxity sorry for this issue, I resolved moving old code from `cypress/support/index.js` to `cypress/support/component.ts`. I also removed the `window.parent` workaround, it was wrong.

Thanks for this plugin!

**Comment by iFaxity** [comment]
Hi @astagi, thanks for the issue!

Great that you found a solution.
