### ISSUE TITLE
Cannot read properties of undefined (reading 'shouldInstrument')

### ISSUE THREAD

**Issue by mat813** [iFaxity/vite-plugin-istanbul#55]
When upgrading to 3.0.3, I get this error.

I don't really know how plugins work, but it seems that testExclude is now filled in asynchronously, and the async call is not done by the time transform gets called.

**Comment by econte-sprig** [comment]
Seeing the same issue, downgrading to 3.0.2 fixed it

**Comment by iFaxity** [comment]
Hi @mat813 and @econte-sprig,

this seems to be an issue with the most recent version v3.0.3 and is caused by #53.
There is a fix ready by @kkrings, #56, that will be published within a couple of minutes.
