### ISSUE TITLE
how to view the html  coverage report?

### ISSUE THREAD

**Issue by kazaff** [iFaxity/vite-plugin-istanbul#57]
Hi there.
I'm a newbe for istanbul. Could you help me?
Thanks in advance.

**Comment by iFaxity** [comment]
Hi @kazaff, this plugin only instruments the code for a code-coverage tool like nyc.
It does not actually generate any code coverage reports, rather it only injects code coverage into the code when Vite is transforming the code.

To actually get the code coverage please use a tool like Cypress (https://www.cypress.io/)
Try setting it up with the help of their getting started guide (https://docs.cypress.io/guides/getting-started/installing-cypress).

There are more code testing tools out there, Cypress is a popular all in one solution to use.
As each tool is different from each other and can vary depending in the setup of the code coverage reporters.

I'm sorry I cant help you more than this, I hope I've at least given you some information in what to look into.

Thanks you @kazaff and have a nice day!

**Comment by kazaff** [comment]
@iFaxity 
Thank you so much.
You have already given me so detail information, I will do some research by myself.
