### ISSUE TITLE
development mode and build mode instrument result is different in SSR project

### ISSUE THREAD

**Issue by sunnywanggit** [iFaxity/vite-plugin-istanbul#67]
### Describe the bug

development mode and build mode instrument result is different in SSR project

development mode：
![image](https://user-images.githubusercontent.com/53786183/211206486-4d6ee406-1424-4b26-b80e-e98d41c194be.png)

build mode：
![image](https://user-images.githubusercontent.com/53786183/211206439-8958ff69-ffd9-4c90-9ab2-c3cfd0b7870a.png)

### Reproduction

https://github.com/sunnywanggit/coverage

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics         
    Memory: 1.17 GB / 15.86 GB
  Binaries:
    Node: 16.14.0 - D:\dachui\install\node\node.EXE
    Yarn: 1.22.15 - D:\dachui\install\node\yarn.CMD
    npm: 8.3.1 - D:\dachui\install\node\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

yarn

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/iFaxity/vite-plugin-istanbul/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/iFaxity/vite-plugin-istanbul/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a vite-plugin-istanbul issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by iFaxity** [comment]
Hi @sunnywanggit,

I'll look at this and see if i can find a cause.

Might be an error when the instrumenter gets the ID for the file as the filenames are different in build and in serve mode.

**Comment by sunnywanggit** [comment]
@iFaxity Thanks a lot

**Comment by iFaxity** [comment]
After looking into this there could be a fix to manipulate the module ID to remove the query parameters after the file path. However not sure what consequence this can have on other setups.

I will try this approach as there seem to not be a fix using Vite/Rollups own API. as getFileName is not valid for the modules and getModuleInfo does not yield anything interesting. The query parameters is only there for the Vue plugin to know how to parse the file, nothing else it seems.

**Comment by iFaxity** [comment]
@sunnywanggit Please try the solution release in the version v4.0.0-rc.2.

If it is ok i will publish it along a release in the future, but for now it is in a release candidate to try out the feature

**Comment by vduggen** [comment]
> @sunnywanggit Please try the solution release in the version v4.0.0-rc.2.
> 
> If it is ok i will publish it along a release in the future, but for now it is in a release candidate to try out the feature

I tested it on version v4.0.0-rc.2 and it's working fine, I was scared because in the beginning it was the cache hahaha, thanks a lot for the project it helped a lot! I felt some difficulties because it doesn't have much content, but I want to see if I contribute to the community.

PS: I'm Brazilian and I'm using google translator, sorry if the translation is bad

**Comment by iFaxity** [comment]
@vduggen No worries I understand you just fine 😊.

Great that the solution worked, I will publish it in a stable release very soon.

Thanks for contributing 👍.
