### ISSUE TITLE
Non tested components are not considered in calculating total coverage 

### ISSUE THREAD

**Issue by radoslavirha** [iFaxity/vite-plugin-istanbul#78]
### Describe the bug

Hi,

I'm using Quasar (built on Vue) and when I run component tests, the total coverage is calculated only from tested components. All the other files are in final report (e.g. with 'text-summary' reporter) but with zeros.

I use  [Quasar testing](https://github.com/quasarframework/quasar-testing) which wraps all the necessary tools.

I described my [issue in Quasar testing repo](https://github.com/quasarframework/quasar-testing/issues/319#issue-1572809922) ^^ and I was pointed to this repo.

![image](https://user-images.githubusercontent.com/23722745/218995879-ebeaac16-e925-4ca4-a641-b86f5b29bcf0.png)

I can see not instrumented files in `./nyc_output/out.json`

```
"component.vue": {
  "path": "component.vue",
  "statementMap": {},
  "fnMap": {},
  "branchMap": {},
  "s": {},
  "f": {},
  "b": {}
}
```

My app is not important in this case, I cloned Quasar testing and played with it and the result is the same.

I tried almost every suggestion I found, but nothing is working and I can't get real coverage for whole project.

Thanks

### Reproduction

https://github.com/quasarframework/quasar-testing

### Steps to reproduce

`git clone https://github.com/quasarframework/quasar-testing.git`
`cd quasar-testing`
`cd test-project-vite`

add to `.nycrc`:
-  `"all": true` (it should extend config, but it's not working for me) 
- `"reporter": ["clover", "json", "text", "lcov", "cobertura", "text-summary", "json-summary"]` (text-summary shows non tested files with zeros in terminal)

`yarn sync:cypress && yarn test:component:ci`

### System Info

```shell
System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1
    Memory: 66.98 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 9.4.1 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.3
```

### Used Package Manager

yarn

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/iFaxity/vite-plugin-istanbul/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/iFaxity/vite-plugin-istanbul/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a vite-plugin-istanbul issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by iFaxity** [comment]
Hello @Radik24, thanks for the issue.

Sorry for the wait, but i will look into this a bit further as it relates to other issues in the past. The root case us that the code coverage reporter does not look at all the included files. Only the files in the coverage report.

Why the uncovered files are not in the report is that we hook into vite transform process, which only transforms files that are imported. Which is one of the main features of Vite.

I have not found a way to include the uncovered files in the report but will look into a way to somehow add them asfterhand. Maybe there is a way to "prepare" a report in a way.

**Comment by iFaxity** [comment]
Closed due to inactivity.
