### ISSUE TITLE
development mode and build mode instrument result is different in normal web project

### ISSUE THREAD

**Issue by calmzhuang** [iFaxity/vite-plugin-istanbul#89]
### Describe the bug
development mode and build mode instrument result is different in normal web project
development mode：
![image](https://user-images.githubusercontent.com/36062221/229081785-f0d89b1f-018c-49d1-8bec-b38921159f3e.png)

build mode：
![image](https://user-images.githubusercontent.com/36062221/229081926-51b9a3ba-ba97-4d90-a011-515aac0a0b50.png)

  Binaries:
    node: v14.18.2
    npm: 6.14.15
   vite-plugin-istanbul:4.0.1
  Browsers:
    Chromium (111.0.5563.110)

Used Package Manager
npm

Logs
No response

**Comment by lipanlowdpr** [comment]
#96

**Comment by iFaxity** [comment]
Hi @calmzhuang,

Could you please try the new rc version released with https://github.com/iFaxity/vite-plugin-istanbul/pull/180 if this fixes your issue?
If there is no problem a release with this will come out to stable within a couple of days.

**Comment by iFaxity** [comment]
Closing until this conversation gets picked up again.

**Comment by posti85** [comment]
I come 2 years latter just to confirm https://github.com/iFaxity/vite-plugin-istanbul/pull/180 fixed that issue.
