### ISSUE TITLE
v2.2.1 breaks existing setups

### ISSUE THREAD

**Issue by nightah** [iFaxity/vite-plugin-istanbul#9]
https://github.com/iFaxity/vite-plugin-istanbul/commit/98bf77dbaa29ee8acfee426ae8177d8a2804a482 introduced a breaking change for existing setups.

We now cannot instrument code with a mode of production because it will bail out after the first conditional is met.

Could we perhaps remove the mode conditional? I would be happy to submit a PR I just would like to understand what would be accepted.

**Comment by iFaxity** [comment]
However you are correct in that the commit in question did break existing setups. But logically the check was too lax, we only want instrumentation if:

1. We are in running Vite in a non production environment
2. The environment variable is false (config dependent) OR true depending on requireEnv is set.
