### ISSUE TITLE
"resolveFilename" causing same named paths in Vue files

### ISSUE THREAD

**Issue by YuWenZhong** [iFaxity/vite-plugin-istanbul#96]
### Describe the bug

The @vitejs/plugin-vue plugin splits Vue files into three parts, which are template, script, and style. If the resolveFilename function directly removes the query string, It may cause issues with same named paths (different parts of the same named Vue file). Therefore, it is recommended to filter Vue files and only instrument the script part, to generate accurate code coverage reports.

### Reproduction

--

### Steps to reproduce

yarn build

### System Info

```shell
node v14.18.1
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/iFaxity/vite-plugin-istanbul/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/iFaxity/vite-plugin-istanbul/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a vite-plugin-istanbul issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by iFaxity** [comment]
Hi @YuWenZhong, thanks for the issue. I will look into this in the coming days.

**Comment by lipanlowdpr** [comment]
i met the same problem. it will generate different window.__coverage__ obj between dev and build enviroment.

**Comment by sawmurai** [comment]
I ran into the same issue and found that it might be possible to pass the `id` instead of the resolved filename to the instrumenter. This fixes it locally for me. I still have up to three coverage functions per .vue file, but they have different names and don't conflict with each other.

**Comment by Mistrain-y-y** [comment]
> I ran into the same issue and found that it might be possible to pass the `id` instead of the resolved filename to the instrumenter. This fixes it locally for me. I still have up to three coverage functions per .vue file, but they use different paths and don't conflict with each other. The resulting report correctly detects the coverage of script part of the vue file.

like this?
```ts
window.__coverage__ = {
"xxxx/program/src/App.vue": {...},
"xxxx/program/src/App.vue?vue&type=script&setup=true&xxxxx": {...},
// ...
}
```

**Comment by sawmurai** [comment]
Yes, exactly. The local change I made was to pass the `id` instead of the `filename` in both calls to `instrumenter.instrumentSync` in https://github.com/iFaxity/vite-plugin-istanbul/blob/next/src/index.ts#L186.

**Comment by Mistrain-y-y** [comment]
> Yes, exactly. The local change I made was to pass the `id` instead of the `filename` in both calls to `instrumenter.instrumentSync` in https://github.com/iFaxity/vite-plugin-istanbul/blob/next/src/index.ts#L186.

But I think the "xxxx/program/src/App.vue" file is useless, which just import the "xxxx/program/src/App.vue?vue&type=script&setup=true&xxxxx" and export.
It seems like all js code is in the "xxxx/program/src/App.vue?vue&type=script&setup=true&xxxxx" file(i am not sure). Is there any solution i can remove or ignore the "xxxx/program/src/App.vue"?

```ts
window.__coverage__ = {
"xxxx/program/src/App.vue": {...},
"xxxx/program/src/App.vue?vue&type=script&setup=true&xxxxx": {...},
// ...
}
```

**Comment by emilepharand** [comment]
I have the same problem in my project.

@sawmurai's solution fixes it for me.

**Comment by Nol-go** [comment]
Reference to issue (179) is wrong, I miss-clicked the real issue I wanted to reference (178). sry

**Comment by Nol-go** [comment]
@iFaxity I've just created a PR for this issue, please do tell me if there's something wrong.

If anyone know how I can use my PR in my project's package.json. Please tell me I can't manage to find anything on google/stackoverflow.

**Comment by lukasbrzobohaty** [comment]
> @iFaxity I've just created a PR for this issue, please do tell me if there's something wrong.
> 
> If anyone knows how I can use my PR in my project's package.json. Please tell me I can't manage to find anything on google/stackoverflow.

Thanks for fix. 
I tried and these changes ignore vue options api now. 
You can try on project what I created for https://github.com/iFaxity/vite-plugin-istanbul/issues/178.

This is debug log of ids what plugin processes:
```
vite v5.1.1 building for production...
.../vite-project/index.html
transforming (1) index.html
.../vite-project/src/main.ts
.../vite-project/src/style.css
.../vite-project/node_modules/vue/dist/vue.runtime.esm-bundler.js
.../vite-project/src/App.vue
transforming (6) src/App.vue
.../vite-project/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js
.../vite-project/src/App.vue?vue&type=style&index=0&scoped=e636f1af&lang.css
.../vite-project/src/App.vue?vue&type=script&setup=true&lang.ts
transforming (11) vite:asset:public/vite.svg
.../vite-project/src/assets/vue.svg
.../vite-project/src/components/HelloWorld2.vue
.../vite-project/node_modules/@vue/shared/dist/shared.esm-bundler.js
.../vite-project/src/components/HelloWorld2.vue?vue&type=style&index=0&scoped=4d3c4b0c&lang.css
.../vite-project/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js
.../vite-project/src/components/HelloWorld.vue
.../vite-project/src/components/HelloWorld.vue?vue&type=style&index=0&scoped=a503fb62&lang.css
.../vite-project/src/components/HelloWorld.vue?vue&type=script&setup=true&lang.ts
.../vite-project/node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js
✓ 20 modules transformed.
```

**Comment by Nol-go** [comment]
> > @iFaxity I've just created a PR for this issue, please do tell me if there's something wrong.
> > If anyone knows how I can use my PR in my project's package.json. Please tell me I can't manage to find anything on google/stackoverflow.
> 
> Thanks for fix. I tried and these changes ignore vue options api now. You can try on project what I created for #178.
> 
> This is debug log of ids what plugin processes:
> 
> ```
> vite v5.1.1 building for production...
> .../vite-project/index.html
> transforming (1) index.html
> .../vite-project/src/main.ts
> .../vite-project/src/style.css
> .../vite-project/node_modules/vue/dist/vue.runtime.esm-bundler.js
> .../vite-project/src/App.vue
> transforming (6) src/App.vue
> .../vite-project/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js
> .../vite-project/src/App.vue?vue&type=style&index=0&scoped=e636f1af&lang.css
> .../vite-project/src/App.vue?vue&type=script&setup=true&lang.ts
> transforming (11) vite:asset:public/vite.svg
> .../vite-project/src/assets/vue.svg
> .../vite-project/src/components/HelloWorld2.vue
> .../vite-project/node_modules/@vue/shared/dist/shared.esm-bundler.js
> .../vite-project/src/components/HelloWorld2.vue?vue&type=style&index=0&scoped=4d3c4b0c&lang.css
> .../vite-project/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js
> .../vite-project/src/components/HelloWorld.vue
> .../vite-project/src/components/HelloWorld.vue?vue&type=style&index=0&scoped=a503fb62&lang.css
> .../vite-project/src/components/HelloWorld.vue?vue&type=script&setup=true&lang.ts
> .../vite-project/node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js
> ✓ 20 modules transformed.
> ```
> 
> `HelloWorld.vue` is composition api and `HelloWorld2.vue` is options api. It seems vue SFC didn't split code to template, style and script for options api, only for composition api.

Hi, sorry the fix didn't hell for option API, I've never used it so I don't really know how it works with vite, also, as I've said in the PR, I had trouble at first because when using composition API we get two id's with query params (one of them is the good one) and another without query so we might be able to add an option to ask if user is using the composition api or the option api, but I can't see how to support a hybrid setup line the one you linked. Maybe using @sawmurai 's fix would work but it might break other things and it might also break the links of the coverage reports. If any of you two have an idea please do share it.
I'll try working on it tomorrow (it's 9:50 PM for me right now) but I have quite a bit of work to do tomorrow.

Also sry for the single block, I'm commenting from my smartphone, i'll fix this later.

**Comment by lukasbrzobohaty** [comment]
@Nol-go Thanks, I appreciate your work. I tried change `filename` to `id`. Instrument it looks fine now and coverage is too. I added example with cypress and coverage report to repo what i created for https://github.com/iFaxity/vite-plugin-istanbul/issues/178.

Could someone create PR with these changes?
